# Generated by Django 3.0.2 on 2020-01-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=254)),
                ('user_id', models.CharField(max_length=254)),
                ('res_id', models.CharField(max_length=254)),
                ('food_item', models.CharField(max_length=254)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=254)),
                ('user_id', models.CharField(max_length=254)),
                ('content', models.TextField(max_length=254)),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Res_Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254)),
                ('res_id', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(max_length=254)),
                ('res_name', models.CharField(max_length=254)),
                ('res_location', models.TextField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254)),
                ('user_name', models.CharField(max_length=254)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_location', models.TextField(max_length=254)),
                ('user_mob_no', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=254)),
                ('res_id', models.CharField(max_length=254)),
                ('review', models.TextField(max_length=254)),
            ],
        ),
    ]
